spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/db_manage?characterEncoding=utf8&useSSL=true
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
  mvc: 
    static-path-pattern: /**
  resources:
    static-locations:
    - /resources/static
#    - C:/workspaces/wp_node/antdp/dist/
  jpa:
    database: MYSQL
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: common.mysql.MySQL5DialectUTF8

server:
  port: 8101


#security:
#  oauth2
#    client:
#      clientId: 233668646673605
#      clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me:

wss:
  server:
    port: 9101